version: "3.7"

services:
  db:
    container_name: my_dating_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "my_dating_test"
    ports:
      - "5432:5432"
    networks:
      - default

  pgadmin:
    container_name: pgadmin4_container_my_dating
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD_FILE}"
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    networks:
      - default

  redis:
    container_name: redis_my_dating
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis:/data

networks:
  default:
    driver: bridge

volumes:
  redis:
    driver: local